account_id = "2043c55714c7228bf7d2190c2ee10822"
name = "cf-worker-status-page-pro"
main = "./src/worker/index.ts"
compatibility_flags = [ "streams_enable_constructors" ]
compatibility_date = "2021-09-29"
workers_dev = true
# npx --no -- wrangler kv:namespace create cf-worker-status-page-pro
kv_namespaces = [ { binding = "KV_STORE", id = "b68d8c6ca9ec4f4e9f12477bb5f9fd12" }, ]

[site]
bucket = "./dist/client"

[dev]
port = 3000

[env.production]
kv_namespaces = [ { binding = "KV_STORE", id = "b68d8c6ca9ec4f4e9f12477bb5f9fd12" }, ]

[env.production.triggers]
crons = [
  # https://crontab.guru/#*/2_*_*_*_*
  # Check monitors
  "*/2 * * * *",
  # https://crontab.guru/#*/10_*_*_*_*
  # Update remote csv monitors
  "*/10 * * * *",
]
